name: Publish Retype powered website to FTP

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to FTP host
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: retypeapp/action-build@latest
      
      - uses: retypeapp/action-git-ftp@latest
        with:
          ftp-host: sftp://${{ secrets.FTP_SERVER }}:22
          ftp-root: ./
          ftp-user: ${{ secrets.FTP_USERNAME }}
          ftp-pass: ${{ secrets.FTP_PASSWORD }}
          update-branch: true