name: Deploy to Emcloud SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code source
        uses: actions/checkout@v4

      - name: ⚙️ Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🔨 Construction du site (Retype)
        run: |
          npm install retypeapp --global
          retype build

      - name: 🚀 Envoi des fichiers via SFTP pur
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 33964
          local_path: './.retype/*'
          remote_path: '/public_html'
          sftp_only: true